spring:
  application:
    name: ride-management-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ridelink_ride_db}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:8083}

services:
  driver:
    base-url: ${DRIVER_SERVICE_URL:http://localhost:8082}
  fare-payment:
    base-url: ${FARE_PAYMENT_SERVICE_URL:http://localhost:8084}

security:
  internal:
    service-key: ${INTERNAL_SERVICE_KEY:}
