spring:
  application:
    name: driver-and-vehicle-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ridelink_driver_db}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:8082}
